# Invoke 'cargo +nightly fmt'.
edition = "2021"
imports_granularity = "Crate"
use_small_heuristics = "Max"
group_imports = "StdExternalCrate"
reorder_modules = true
reorder_imports = true
format_strings = true
match_block_trailing_comma = true
merge_derives = true
reorder_impl_items = true